roles:
  administrator:
    name: IEEE Administrator
    badge: badge-warning
    permissions: [view, edit, manage]

  officer:
    name: IEEE Officer
    badge: badge-info
    permissions: [view, edit]

  sponsor:
    name: IEEE Sponsor
    badge: badge-warning
    permissions: [view]

  member:
    name: Regular Member
    badge: badge-neutral
    permissions: [self]

resume:
  allowedTypes: [.pdf, .doc, .docx]
  maxSize: 5242880 # 5MB in bytes
  viewer:
    width: w-11/12
    maxWidth: max-w-5xl
    height: h-[80vh]

ui:
  transitions:
    fadeDelay: 50

  messages:
    memberId:
      saving: Saving member ID...
      success: IEEE Member ID saved successfully!
      error: Failed to save IEEE Member ID. Please try again.
      messageTimeout: 3000

    resume:
      uploading: Uploading resume...
      success: Resume uploaded successfully!
      error: Failed to upload resume. Please try again.
      deleting: Deleting resume...
      deleteSuccess: Resume deleted successfully!
      deleteError: Failed to delete resume. Please try again.
      messageTimeout: 3000

    event:
      saving: Saving event...
      success: Event saved successfully!
      error: Failed to save event. Please try again.
      deleting: Deleting event...
      deleteSuccess: Event deleted successfully!
      deleteError: Failed to delete event. Please try again.
      messageTimeout: 3000
      checkIn:
        checking: Checking event code...
        success: Successfully checked in to event!
        error: Failed to check in. Please try again.
        invalid: Invalid event code. Please try again.
        expired: This event is not currently active.
        alreadyCheckedIn: You have already checked in to this event.
        messageTimeout: 3000

    auth:
      loginError: Failed to start authentication
      notSignedIn: Not signed in
      notVerified: Not verified
      notProvided: Not provided
      notAvailable: Not available
      never: Never

  tables:
    events:
      title: Event Management
      editor_title: Event Details
      columns:
        event_name: Event Name
        event_id: Event ID
        event_code: Event Code
        start_date: Start Date
        end_date: End Date
        points_to_reward: Points to Reward
        location: Location
        registered_users: Registered
        actions: Actions
      form:
        event_id:
          label: Event ID
          placeholder: Enter unique event ID
        event_name:
          label: Event Name
          placeholder: Enter event name
        event_code:
          label: Event Code
          placeholder: Enter check-in code
        start_date:
          date_label: Start Date for check-in
          time_label: Start Time for check-in
          date_placeholder: Select start date for check-in
          time_placeholder: Select start time for check-in
        end_date:
          date_label: End Date for check-in
          time_label: End Time for check-in
          date_placeholder: Select end date for check-in
          time_placeholder: Select end time for check-in
        points_to_reward:
          label: Points to Reward
          placeholder: Enter points value
        location:
          label: Location
          placeholder: Enter event location
        files:
          label: Event Files
          help_text: Upload event-related files (PDF, DOC, DOCX, TXT, JPG, JPEG, PNG)
        buttons:
          save: Save
          cancel: Cancel
          edit: Edit
          delete: Delete

  defaults:
    pageSize: 50
    sortField: -updated

autoDetection:
  officer:
    emailDomain: "@ieeeucsd.org"
